"""Diagnostics Module

This provides some diagnostic features.

The heart beat runs continuously, flashing the on board led.



"""
"""       Copyright 2026  Paul Redhead

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""

import asyncio, sys, time
from machine import Pin
from device import Device


def log_event(report):
    """ Log event report.
    
    This logs an event report as generated by Device.report_event().
    
    The event is logged using print - defaults to REPL out.
    The log level is controlled via sys.argv item 1.
    
    The first item may be set to a string of characters. Each character enables logging
    reports from a specific source as identified in the base Device class.

    characters are:
        - w: wifi
        - m: MQTT
        - l: local RailCom detector
        - d: block occupancy detector
        - g: global detector

    E.g. setting the first argument to 'wm' will log both wifi and mqtt events.
    Settings are case sensitive and must be lower case.

    args:
        report: the report as generated by the source object.
    """
    if sys.argv:
        src, event, data = report
        if src.type in sys.argv[0]:
            t = time.localtime()

            print(f'{t[3]:02}:{t[4]:02}:{t[5]:02} '
                    f'{src.__class__.__name__:10} {src.name:6} {event} {data}')


class HeartBeat(Device):
    """ Heart Beat
    
    This singleton class runs an asycio task to flash the Pico on board
    LED once per second."""

    _hb = None  # singleton reference - will be set on instantiation


    @classmethod
    def get_instance(cls):
        """Return the singleton instance

        The singleton is created on the first call.
        """
        if cls._hb is None:
            HeartBeat()
        return cls._hb
    
    def __init__(self):
        """Heart Beat Constructor
        
        Initiate the on board LED GPIO and create the asynchio task to flash it."""
        HeartBeat._bh = self
        self._led = Pin("LED", Pin.OUT)
        asyncio.create_task(self._flash_led())
        super().__init__('hb', 'h')

    async def _flash_led(self):
        """Flash the LED on board LED"""
        while True:
            self._led.on()
            await asyncio.sleep_ms(100)
            self._led.off()
            await asyncio.sleep_ms(900)